- hosts: webservers
  become: yes
  tasks:
  - name: Install all packages
    package:
      name: "{{ item }}"
      state: present
    loop:
      - "openjdk-8-jdk"
      - "tomcat8"
      - "apache2"
    notify:
      - "enable and restart {{ item }}"
  handlers:
  - name: "enable and restart {{ item }}"
    service:
      name: "{{ item }}"
      enabled: yes
      state: restarted
